---
- name: "LOW | WN19-SO-000140 | Windows Server 2019 title for the legal banner must be configured with the appropriate text."
  win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
      value: LegalNoticeCaption
      data: "{{ wn19stig_legalnoticecaption }}"
      datatype: string
  when:
      - wn19_so_000140
  tags:
      - WN19-SO-000140
      - V-205632
      - SRG-OS-000023-GPOS-00006
      - SRG-OS-000228-GPOS-00088
      - SV-205632r569188_rule
      - CCI-000048
      - CCI-001384
      - CCI-001385
      - CCI-001386
      - CCI-001387
      - CCI-001388

- name: "LOW | WN19-00-000180 | Windows Server 2019 non-administrative accounts or groups must only have print permissions on printer shares."
  block:
      - name: "LOW | WN19-00-000180 | Windows Server 2019 non-administrative accounts or groups must only have print permissions on printer shares."
        debug:
            msg: "Warning!! This is a manual task. Windows Server 2019 non-administrative accounts or groups must only have print permissions on printer shares."

      - name: "LOW | WN19-00-000180 | Windows Server 2019 non-administrative accounts or groups must only have print permissions on printer shares. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'wn19_00_000180'
  when:
      - wn19_00_000180
  tags:
      - WN19-00-000180
      - V-205664
      - SRG-OS-000080-GPOS-00048
      - SV-205664r569188_rule
      - CCI-000213
      - CAT3

- name: "LOW | WN19-CC-000200 | Windows Server 2019 Application Compatibility Program Inventory must be prevented from collecting data and sending the information to Microsoft."
  win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppCompat
      value: DisableInventory
      data: 1
      datatype: dword
  when:
      - wn19_cc_000200
  tags:
      - WN19-CC-000200
      - V-205691
      - SRG-OS-000095-GPOS-00049
      - SV-205691r569188_rule
      - CCI-000381
      - CAT3

- name: "LOW | WN19-DC-000160 | Windows Server 2019 directory service must be configured to terminate LDAP-based network connections to the directory server after 5 minutes of inactivity."
  block:
      - name: "LOW | WN19-DC-000160 | Windows Server 2019 directory service must be configured to terminate LDAP-based network connections to the directory server after 5 minutes of inactivity."
        debug:
            msg: "Warning!! This is a manual task. Windows Server 2019 directory service must be configured to terminate LDAP-based network connections to the directory server after 5 minutes of inactivity."

      - name: "LOW | WN19-DC-000160 | Windows Server 2019 directory service must be configured to terminate LDAP-based network connections to the directory server after 5 minutes of inactivity. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN19-DC-000160'
  when:
      - wn19_dc_000160
  tags:
      - WN19-DC-000160
      - V-205726
      - SRG-OS-000163-GPOS-00072
      - SV-205726r569188_rule
      - CCI-001133
      - CAT3

- name: "LOW | WN19-00-000440 | The Windows Server 2019 time service must synchronize with an appropriate DoD time source."
  block:
      - name: "LOW | WN19-00-000440 | The Windows Server 2019 time service must synchronize with an appropriate DoD time source."
        debug:
            msg: "Warning!! This is a manual task. The Windows Server 2019 time service must synchronize with an appropriate DoD time source. "

      - name: "LOW | WN19-00-000440 | The Windows Server 2019 time service must synchronize with an appropriate DoD time source. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'wn19_00_000440'
  when: wn19_00_000440
  tags:
      - WN19-00-000440
      - V-205800
      - SRG-OS-000355-GPOS-00143
      - SV-205800r859311_rule
      - CCI-001891
      - CAT3

- name: "LOW | WN19-CC-000060 | Windows Server 2019 Must be configured to ignore NetBIOS name release requests except from WINS servers."
  win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Netbt\Parameters
      value: NoNameReleaseOnDemand
      data: 1
      datatype: dword
  when:
      - wn19_cc_000060
  tags:
      - WN19-CC-000060
      - V-205819
      - SRG-OS-000420-GPOS-00186
      - SV-205819r569188_rule
      - CCI-002385
      - CAT3

- name: "LOW | WN19-00-000460 | Windows Server 2019 systems must have Unified Extensible Firmware Interface (UEFI) firmware and be configured to run in UEFI mode, not Legacy BIOS."
  block:
      - name: "LOW | WN19-00-000460 | Windows Server 2019 systems must have Unified Extensible Firmware Interface (UEFI) firmware and be configured to run in UEFI mode, not Legacy BIOS."
        debug:
            msg: "Warning!! This is a manual task. Windows Server 2019 systems must have Unified Extensible Firmware Interface (UEFI) firmware and be configured to run in UEFI mode, not Legacy BIOS."

      - name: "LOW | WN19-00-000460 | Windows Server 2019 systems must have Unified Extensible Firmware Interface (UEFI) firmware and be configured to run in UEFI mode, not Legacy BIOS. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'wn19_00_000460'
  when:
      - wn19_00_000460
  tags:
      - WN19-00-000460
      - V-205856
      - SRG-OS-000480-GPOS-00227
      - SV-205856r569188_rule
      - CCI-000366
      - CAT3

- name: "LOW | WN19-00-000470 | Windows Server 2019 must have Secure Boot enabled."
  block:
      - name: "LOW | WN19-00-000470 | Windows Server 2019 must have Secure Boot enabled."
        debug:
            msg: "Warning!! This is a manual task. Windows Server 2019 must have Secure Boot enabled. "

      - name: "LOW | WN19-00-000470 | Windows Server 2019 must have Secure Boot enabled. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'wn19_00_000470'
  when:
      - wn19_00_000470
  tags:
      - WN19-00-000470
      - V-205857
      - SRG-OS-000480-GPOS-00227
      - SV-205857r569188_rule
      - CCI-000366
      - CAT3

- name: "LOW | WN19-CC-000030 | Windows Server 2019 internet Protocol version 6 (IPv6) source routing must be configured to the highest protection level to prevent IP source routing."
  win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
      value: DisableIPSourceRouting
      data: 2
      datatype: dword
  when:
      - wn19_cc_000030
  tags:
      - WN19-CC-000030
      - V-205858
      - SRG-OS-000480-GPOS-00227
      - SV-205858r569188_rule
      - CCI-000366
      - CAT3

- name: "LOW | WN19-CC-000040 | Windows Server 2019 source routing must be configured to the highest protection level to prevent Internet Protocol (IP) source routing."
  win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      value: DisableIPSourceRouting
      data: 2
      datatype: dword
  when:
      - wn19_cc_000040
  tags:
      - WN19-CC-000040
      - V-205859
      - SRG-OS-000480-GPOS-00227
      - SV-205859r569188_rule
      - CCI-000366
      - CAT3

- name: "LOW | WN19-CC-000050 | Windows Server 2019 must be configured to prevent Internet Control Message Protocol (ICMP) redirects from overriding Open Shortest Path First (OSPF)-generated routes."
  win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      value: EnableICMPRedirect
      data: 0
      datatype: dword
  when:
      - wn19_cc_000050
  tags:
      - WN19-CC-000050
      - V-205860
      - SRG-OS-000480-GPOS-00227
      - SV-205860r569188_rule
      - CCI-000366
      - CAT3

- name: "LOW | WN19-CC-000260 | Windows Server 2019 Windows Update must not obtain updates from other PCs on the Internet."
  win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization
      value: DODownloadMode
      data: 1
      datatype: dword
  when:
      - wn19_cc_000260
  tags:
      - WN19-CC-000260
      - V-205870
      - SRG-OS-000480-GPOS-00227
      - SV-205870r569188_rule
      - CCI-000366
      - CAT3

- name: "LOW | WN19-CC-000320 | Windows Server 2019 turning off File Explorer heap termination on corruption must be disabled."
  block:
      - name: "LOW | WN19-CC-000320 | Windows Server 2019 turning off File Explorer heap termination on corruption must be disabled."
        debug:
            msg: "Warning!! This is a manual task. Windows Server 2019 turning off File Explorer heap termination on corruption must be disabled. "

      - name: "LOW | WN19-CC-000320 | Windows Server 2019 turning off File Explorer heap termination on corruption must be disabled. | import reuseable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'wn19_cc_000320'
  when:
      - wn19_cc_000320
  tags:
      - WN19-CC-000320
      - SV-205871r569188_rule
      - V-205871
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - CAT3

- name: "LOW | WN19-SO-000370 | Windows Server 2019 default permissions of global system objects must be strengthened."
  win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager
      value: ProtectionMode
      data: 1
      datatype: string
  when:
      - wn19_so_000370
  tags:
      - WN19-SO-000370
      - V-205871
      - SRG-OS-000480-GPOS-00227
      - SV-205871r569188_rule
      - CCI-000366
      - CAT3
