---

- name: "PRELIM | Detect if Trusted Platform Module (TPM) is available"
  ansible.windows.win_shell: (Get-CimInstance -ClassName Win32_OperatingSystem).ProductType
  changed_when: false
  failed_when: false
  register: win2019_tpm_enabled
  tags:
      - always

# hvm is for Amazon AMI's, Hyper-V we have found for Azure, kvm is used for ('QEMU', 'Amazon EC2', 'DigitalOcean', 'Google', 'Scaleway', 'Nutanix', 'KVM', 'KVM Server', 'Bochs', 'AHV')
# This list is not complete and will be updated as we try on more cloud based services.
# As of now testing is working in Azure using Hyper-V. We are currently using this for reference:
# https://github.com/ansible/ansible/blob/905131fc76a07cf89dbc8d33e7a4910da3f10a16/lib/ansible/module_utils/facts/virtual/linux.py#L205
- name: Set Fact If Cloud Based System.
  ansible.builtin.set_fact:
      win19stig_cloud_based_system: true
  when:
      - ansible_virtualization_type == 'Hyper-V' or
        ansible_virtualization_type == 'hvm' or
        ansible_virtualization_type == 'kvm'
  tags:
      - always

- name: Get Drive Letters"
  ansible.windows.win_shell: Get-Volume | ?{ $_.DriveType -eq 'Fixed' } | Select-Object -ExpandProperty 'DriveLetter'
  changed_when: false
  failed_when: false
  register: wn19_drive_letters
  when:
      - wn19_00_000240 or
        wn19_au_000060 or
        wn19_00_000390 or
        wn19_00_000400

- name: Check For SecGuide.admx In PolicyDefinitions
  ansible.windows.win_find:
      paths: '{{ item }}:\Windows\PolicyDefinitions'
      patterns: SecGuide.admx
      hidden: true
  changed_when: false
  failed_when: false
  with_items:
      - "{{ wn19_drive_letters.stdout_lines }}"
  register: wn19_secguide_admx_audit
  when:
      - wn19_00_000390 or
        wn19_00_000400

- name: Check For SecGuide.admx In PolicyDefinitions\en-US
  ansible.windows.win_find:
      paths: '{{ item }}:\Windows\PolicyDefinitions\en-US'
      patterns: SecGuide.adml
      hidden: true
  changed_when: false
  failed_when: false
  with_items:
      - "{{ wn19_drive_letters.stdout_lines }}"
  register: wn19_secguide_adml_audit
  when:
      - wn19_00_000390 or
        wn19_00_000400
