---

- name: "PRELIM | Detect if Trusted Platform Module (TPM) is available"
  ansible.windows.win_shell: (Get-CimInstance -ClassName Win32_OperatingSystem).ProductType
  changed_when: false
  failed_when: false
  register: win2019_tpm_enabled
  tags:
      - always

- name: Set Fact If Non-Cloud Based System.
  ansible.builtin.set_fact:
      wn19stig_cloud_based_system: true
  when:
      - ansible_virtualization_type == 'Hyper-V'
  tags:
      - always

# 1 = disabled 0 = enabled
# this reg key may be useful detect is secure conenctions enabled, etc?
- name: "PRELIM | Detect if Remote Desktop Services (RDP) is enabled"
  ansible.windows.win_reg_stat:
      path: HKLM:\System\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
  changed_when: false
  failed_when: false
  register: win2019_rdp_enabled
  tags:
      - always

# remove this debug or set a verb level
- name: win2019_rdp_enabled.value var
  ansible.builtin.debug:
      var: win2019_rdp_enabled.value
