---

- name: "LOW | WN19-CC-000030 | PATCH | Windows Server 2019 Internet Protocol version 6 (IPv6) source routing must be configured to the highest protection level to prevent IP source routing."
  when: wn19_cc_000030 | bool
  tags:
    - WN19-CC-000030
    - CAT3
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-205858r991589_rule
    - V-205858
    - NIST800-53R4_CM-6
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
    value: DisableIPSourceRouting
    data: 2
    datatype: dword

- name: "LOW | WN19-CC-000040 | PATCH | Windows Server 2019 source routing must be configured to the highest protection level to prevent Internet Protocol (IP) source routing."
  when: wn19_cc_000040 | bool
  tags:
    - WN19-CC-000040
    - CAT3
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-205859r991589_rule
    - V-205859
    - NIST800-53R4_CM-6
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    value: DisableIPSourceRouting
    data: 2
    datatype: dword

- name: "LOW | WN19-CC-000050 | PATCH | Windows Server 2019 must be configured to prevent Internet Control Message Protocol (ICMP) redirects from overriding Open Shortest Path First (OSPF)-generated routes."
  when: wn19_cc_000050 | bool
  tags:
    - WN19-CC-000050
    - CAT3
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-205860r991589_rule
    - V-205860
    - NIST800-53R4_CM-6
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    value: EnableICMPRedirect
    data: 0
    datatype: dword

- name: "LOW | WN19-CC-000060 | PATCH | Windows Server 2019 Must be configured to ignore NetBIOS name release requests except from WINS servers."
  when: wn19_cc_000060 | bool
  tags:
    - WN19-CC-000060
    - CAT3
    - CCI-002385
    - SRG-OS-000420-GPOS-00186
    - SV-205819r958902_rule
    - V-205819
    - NIST800-53R4_SC-5
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Netbt\Parameters
    value: NoNameReleaseOnDemand
    data: 1
    datatype: dword

- name: "LOW | WN19-CC-000200 | PATCH | Windows Server 2019 Application Compatibility Program Inventory must be prevented from collecting data and sending the information to Microsoft."
  when: wn19_cc_000200 | bool
  tags:
    - WN19-CC-000200
    - CAT3
    - CCI-000381
    - SRG-OS-000095-GPOS-00049
    - SV-205691r958478_rule
    - V-205691
    - NIST800-53R4_CM-7
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppCompat
    value: DisableInventory
    data: 1
    datatype: dword

- name: "LOW | WN19-CC-000260 | PATCH | Windows Server 2019 Windows Update must not obtain updates from other PCs on the Internet."
  when: wn19_cc_000260 | bool
  tags:
    - WN19-CC-000260
    - CAT3
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-205870r991589_rule
    - V-205870
    - NIST800-53R4_CM-6
  block:
    - name: "LOW | WN19-CC-000260 | AUDIT | Windows Server 2019 Windows Update must not obtain updates from other PCs on the Internet. "
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an incorrect value set for win19stig_dodownloadmode please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."
      when: win19stig_dodownloadmode > 2 and win19stig_dodownloadmode != 99 and win19stig_dodownloadmode != 100

    - name: "LOW | WN19-00-000440 | AUDIT | The Windows Server 2019 time service must synchronize with an appropriate DoD time source. | Warn Count."
      vars:
        warn_control_id: 'LOW | WN19-CC-000260'
      ansible.builtin.import_tasks: warning_facts.yml
      when: win19stig_dodownloadmode > 2 and win19stig_dodownloadmode != 99 and win19stig_dodownloadmode != 100

    - name: "LOW | WN19-CC-000260 | PATCH | Windows Server 2019 Windows Update must not obtain updates from other PCs on the Internet. | Set Variable."
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization
        value: DODownloadMode
        data: "{{ win19stig_dodownloadmode }}"
        datatype: dword
      when: win19stig_dodownloadmode <= 2 or win19stig_dodownloadmode == 99 or win19stig_dodownloadmode == 100

- name: "LOW | WN19-CC-000320 | PATCH | Windows Server 2019 turning off File Explorer heap termination on corruption must be disabled."
  when: wn19_cc_000320 | bool
  tags:
    - WN19-CC-000320
    - CAT3
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-205871r991589_rule
    - V-205871
    - NIST800-53R4_CM-6
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer\
    value: NoHeapTerminationOnCorruption
    state: present
    data: 0
    datatype: dword
